### ISSUE TITLE
TypeError: teleport(): 1st arg can't be coerced to org.bukkit.Location, org.bukkit.entity.Entity

### ISSUE THREAD

**Issue by equisde** [pyplugins/pyplugins#1]
Hello i been trying to create a sethome plugin
so i'm using a api to save the home of the user with the users location on a json file

but when i try to teleport a player i got a TypeError
`TypeError: teleport(): 1st arg can't be coerced to org.bukkit.Location, org.bukkit.entity.Entity
`
my json file contains the following

`{"result": true, "player_name": "Parallax", "location": ["Location{world=CraftWorld{name=world},x=225.0,y=68.0,z=-146.0,pitch=37.649994,yaw=-22.8}"]}`

this is my home command to teleport to "home"

```
def homeCommand(self, sender, command, label, args):
        sender_name = sender.getName()
        location = self.plugin.gethomeApi(sender_name)
        self.plugin.logger.info("location: "+str(location))
        w = location["location"][0][0]
        #x = location["location"][0][1]
        #y = location["location"][0][2]
        #z = location["location"][0][3]
        self.plugin.logger.info(w)
        sender.teleport(w)
        return True
```
in my getHomeApi  i have the user location that i can access with location["location"][0][0] but at the moment of teleport the error comes in
```
i'm importing the next on my plugin
import os
import platform
import urllib
import json
from org.bukkit import Location
from org.bukkit.entity import Player

```

any idea?

**Comment by dmytrohoi** [comment]
Hi, it looks like you are trying to teleport CommandSender.

Could you please check that the CommandSender is instance of Entity (Player).

NOTE: teleport() method can't be called from the CONSOLE.

**Comment by equisde** [comment]
when i try to instance Player() this is what i get  No visible constructors for class (org.bukkit.entity.Player)
i don't know if i'm doing it by the right way 
i'm calling it by the command /home in the game chatbox
w= "Location{world=CraftWorld{name=world},x=225.0,y=68.0,z=-146.0,pitch=37.649994,yaw=-22.8}"
player = Player()
player.teleport(w)

**Comment by equisde** [comment]
i've read that jython has a registry file where i had to add python.security.respectJavaAccessibility = false but i had no luck with it i got attribute error on self.plugin.logger.info so i deleted that line on the registry file

and now i tried to instance i'm importing entity as p 
player = p.Player()
player.teleport(w)
and i got error
Caused by: org.python.core.PyException: TypeError: teleport(): expected 2-3 args; got 1

**Comment by equisde** [comment]
i leave this closed since i was passing the location as a string so i used teleport using getWorld and floating x y z everything works fine thanks!
