### ISSUE TITLE
Is this still actively being developed?

### ISSUE THREAD

**Issue by fnrcum** [pyplugins/pyplugins#2]
I really like where this was going and am planning on supporting it on my PaperMC server and even building a few plugins but I would like to know if it still has any active development?
Also are we planning on supporting the Jython 3 when it's out?

**Comment by dmytrohoi** [comment]
Yeah, it still doesn't require specific version of Minecraft/AnyServer.

I'm not planning any major updates because it's not necessary for now.

Updating to Jython 3 in plan's, but currently can't be estimated as you understand.

**Comment by fnrcum** [comment]
Thanks for the info, In this case i'll be going ahead and building some plugins, maybe we can feature them as proof of the development.
I'm going to be testing it under java 16 as Minecraft 1.17 will require java `x >= 16`
Ah and I was wondering if anyone has ever profiled the implementation to see how "performant" it is. I'm not a java whiz but this is usually what many server owners look at as well.

**Comment by dmytrohoi** [comment]
Sounds good! Thank you for an idea, I will think about it and maybe try to do.

Could you please report to me if you're will find a bugs and etc.
